import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata = {
    title: 'ElectricPro',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="navbar">
                    <div className="naming">
                        <h1>welcome to the ElectricPro</h1>
                    </div>

                    <div className="links">
                        <a href="/services">Services</a>
                        <a href="/contact">Contact</a>
                        <a href="/about">About</a>
                    </div>
                </div>
                {children}
            </body>
        </html>
    );
}
